# -*- coding: utf-8 -*-
"""wttsaap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DR8fQEc3ODV0YuoDp9Ov8IskPGOaNt4r
"""

# Commented out IPython magic to ensure Python compatibility.
import regex
import pandas as pd
import numpy as np
import emoji
import plotly.express as px
from collections import Counter
import matplotlib.pyplot as plt
from os import path
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
# % matplotlib inline

"""### WhatsApp Group Chat Analysis
Althoughts,the data is already to use we still need to change the format of the data and time of message which can be done easily .For this i will define a funciton that can detect whether each line starts with a date as it starts that it is unique messagae:
"""

def startsWithDateAndTime(s):
    pattern = '^([0-9]+)(\/)([0-9]+)(\/)([0-9]+), ([0-9]+):([0-9]+)[ ]?(AM|PM|am|pm)? -' 
    result = re.match(pattern, s)
    if result:
        return True
    return False

"""#### Now i will create a function to extract the username in the chats as Authors:"""

def FindAuthor(s):
  s=s.split(":")
  if len(s)==2:
    return True
  else:
    return False

"""#### Now i will create a function to separate all the function from each other so that we could easily use the information as a pandas datframe:"""

def getDataPoint(line):
  splitLine=line.split(' _ ')
  dataTime=splitLine[0]
  data,time=dataTime.split(', ')
  messgae=' '.join(splitLine[1:])
  if FindAuthor(messgae):
    splitMessage=message.split(': ')
    author=splitMessage[0]
    message=' '.join(splitMessage[1:])
  else:
    author=None
  return date,time,author,message

"""#### The code below will help you to get the data,if you are using an IDE or jupyter notebook or GOoogle colab on anything,you can use the below ,you just need to make sure that you write the complete path of your dataset if you are not using colab or notebook

"""

from google.colab import files
uploaded = files.upload()
data = [] # List to keep track of data so it can be used by a Pandas dataframe
conversation = 'Whatsapp_chat.txt'
with open(conversation, encoding="utf-8") as fp:
    fp.readline() # Skipping first line of the file because contains information related to something about end-to-end encryption
    messageBuffer = [] 
    date, time, author = None, None, None
    while True:
        line = fp.readline() 
        if not line: 
            break
        line = line.strip() 
        if startsWithDateAndTime(line): 
            if len(messageBuffer) > 0: 
                parsedData.append([date, time, author, ' '.join(messageBuffer)]) 
            messageBuffer.clear() 
            date, time, author, message = getDataPoint(line) 
            messageBuffer.append(message) 
        else:
            messageBuffer.append(line)

